#!/usr/bin/env bash
# Initialize local env for the comparative-genomics workflow (anonymized).

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${PROJECT_ROOT}"

echo "=========================================="
echo "  Workflow init"
echo "=========================================="

if command -v conda >/dev/null 2>&1; then
  echo "  conda: $(conda info --base)"
else
  echo "  WARN: conda not in PATH"
fi

RESULTS_DIR="${PROJECT_ROOT}/old_reults/results"
SCRIPTS_DIR="${PROJECT_ROOT}/annotation/scripts"
ANNOTATION_DIR="${PROJECT_ROOT}/old_reults/annotation"
COMPARATIVE_DIR="${PROJECT_ROOT}/comparative_genomics"
LOGS_DIR="${COMPARATIVE_DIR}/logs"
TOOLS_DIR="${PROJECT_ROOT}/old_reults/tools"
RNA_DIR="${PROJECT_ROOT}/old_reults/rna_rawdata"
CONFIG_DIR="${PROJECT_ROOT}/config"

for dir in "$RESULTS_DIR" "$SCRIPTS_DIR" "$ANNOTATION_DIR" "$COMPARATIVE_DIR" "$LOGS_DIR" "$CONFIG_DIR"; do
  mkdir -p "$dir"
  echo "  dir: $dir"
done

if [[ ! -f "${CONFIG_DIR}/species.csv" && -f "${CONFIG_DIR}/../old_reults/species_list.example.csv" ]]; then
  :
fi
[[ -f "${CONFIG_DIR}/species.csv" ]] || echo "  WARN: missing config/species.csv"

T01=""
T02=""
for f in \
  "${RESULTS_DIR}/targets/T01/T01.Chr.final.fa" \
  "${RESULTS_DIR}/genomes/T01.Chr.final.fa" \
  "${PROJECT_ROOT}/new_anno/T01.final.cds.fa"
 do
  [[ -f "$f" ]] && T01="$f" && break
done
for f in \
  "${RESULTS_DIR}/targets/T02/T02.Chr.final.fa" \
  "${RESULTS_DIR}/genomes/T02.Chr.final.fa" \
  "${PROJECT_ROOT}/new_anno/T02.final.cds.fa"
 do
  [[ -f "$f" ]] && T02="$f" && break
done

ENV_FILE="${PROJECT_ROOT}/.project_env"
cat > "${ENV_FILE}" << EOF
# Generated by old_reults/init_project.sh — do not commit
export PROJECT_ROOT="${PROJECT_ROOT}"
export RESULTS_DIR="${RESULTS_DIR}"
export SCRIPTS_DIR="${SCRIPTS_DIR}"
export ANNOTATION_DIR="${ANNOTATION_DIR}"
export COMPARATIVE_DIR="${COMPARATIVE_DIR}"
export CG_SCRIPTS_DIR="${COMPARATIVE_DIR}/scripts"
export LOGS_DIR="${LOGS_DIR}"
export TOOLS_DIR="${TOOLS_DIR}"
export RNA_DIR="${RNA_DIR}"
export CONFIG_DIR="${CONFIG_DIR}"
export SPECIES_CSV="${CONFIG_DIR}/species.csv"
export T01_GENOME="${T01}"
export T02_GENOME="${T02}"
export THREADS=32
export CONDA_ENV=comparative
EOF

echo "  wrote ${ENV_FILE}"
echo "  next: edit config/species.csv paths, then source .project_env"
echo "  run:  ./run_all.sh list   or   make help"
